
src: 
	mkdir src
	git config --global user.name "Maximiliano Usich"
	git config --global user.email maximilianou@gmail.com
	git config --global core.editor vi
	git clone http://gitlab.com/maximilianou/todo
	git clone http://gitlab.com/maximilianou/weekly01
	git clone http://gitlab.com/maximilianou/weekly02
	git clone http://gitlab.com/maximilianou/weekly03
	git clone http://gitlab.com/maximilianou/weekly04
	git clone http://gitlab.com/maximilianou/weekly05
	git clone http://gitlab.com/maximilianou/weekly06
node:
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
	nvm install 13
