
src: 
	mkdir src
	git clone http://gitlab.com/maximilianou/todo
	git clone http://gitlab.com/maximilianou/weekly01
	git clone http://gitlab.com/maximilianou/weekly02
	git clone http://gitlab.com/maximilianou/weekly03
	git clone http://gitlab.com/maximilianou/weekly04
	git clone http://gitlab.com/maximilianou/weekly05
	git clone http://gitlab.com/maximilianou/weekly06
